default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"] || "~/.appstoreconnect/private_keys/AuthKey_#{ENV['ASC_KEY_ID']}.p8"
    )

    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      xcargs: "-authenticationKeyID #{ENV['ASC_KEY_ID']} -authenticationKeyIssuerID #{ENV['ASC_ISSUER_ID']} -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_#{ENV['ASC_KEY_ID']}.p8 -allowProvisioningUpdates",
      export_options: {
        method: "app-store",
        teamID: ENV["APPLE_TEAM_ID"],
        signingStyle: "automatic"
      }
    )

    unless ENV["SKIP_UPLOAD"] == "true"
      upload_to_testflight(
        api_key: api_key,
        skip_waiting_for_build_processing: true
      )
    end
  end
end
