default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      export_options: "../ExportOptions.plist"
    )
    upload_to_testflight
  end
end
